<?php

/**
 * ANVol Role
 * Handles role lookup for ANVol custom modules - this is necessary because the role names will potentially change, but
 * we don't want to refer to the role ids directly, so we're using internal names and resolving them to the correct id.
 * @author  andyw@circle, 02/06/2014
 * @package av_role
 */

function av_role_is_admin($uid) { 
    return av_role_has_roles(user_load($uid), 'website admin', 'IT4C Administrator', 'Regional Co-ordinator', 'Analyst');
}

/**
 * Module basically provides this function for role lookup
 * First arg can be a user object followed by a list of internal role names, or args can be just a list of role names,
 * in which case we check the roles of the currently logged in user.
 * @return bool
 */
function av_role_has_roles() {

    $arguments = func_get_args();
    $role_map  = _av_role_get_role_map();

    # if first argument is user object, use that - otherwise, assume current user
    if (is_object(reset($arguments)))
        $user = array_shift($arguments); 
    else global $user;

    # iterate through roles, perform $role_map lookup, and attempt to match rid
    foreach ($arguments as $role)
        if (isset($user->roles[$role_map[$role]]))
            return true;

    return false;

}

/**
 * Function like the one above - this version checks if the last part of the url is a uid and,
 * if so, checks the roles of that user - otherwise checks the roles of the currently logged in user
 * @return bool
 */
function av_role_has_roles_inherit() {

    $arguments = func_get_args();
    $role_map  = _av_role_get_role_map(); 
    $url_args  = explode('/', $_GET['q']);

    if (count($url_args) >= 3 and is_numeric($subject_uid = end($url_args))) {
        
        # perform additional check that logged in user is an admin before going down this
        # route - the end result is the ability to edit someone else's contact record, so
        # double-check there are a privileged user 
        global $user;
        
        if (av_role_is_admin($user->uid)) {
            
            # if so, load the user who's roles we're interested in
            $subject_user = user_load($subject_uid);
        
            # iterate through roles, perform $role_map lookup, and attempt to match rid
            foreach ($arguments as $role)
                if (isset($subject_user->roles[$role_map[$role]]))
                    return true;

            return false;

        } 
    
    # if not will check the roles of the currently logged in user
    } else global $user;
    
    # iterate through roles, perform $role_map lookup, and attempt to match rid
    foreach ($arguments as $role)
        if (isset($user->roles[$role_map[$role]]))
            return true;
    
    return false;

}

/**
 * Return an array mapping internal role names to ids
 * @return array
 */
function _av_role_get_role_map() {
    
    # resolve internal role names to rids
    static $role_map = array(
        'anonymous user'        => 1, 
        'AbilityNet HR'         => 12,
        'website admin'         => 3,
        'Website editor'        => 5,
        'Individual Volunteer'  => 7,
        'Company Volunteer'     => 8,
        'authenticated user'    => 2,
        'IT4C Administrator'    => 3,
        'Charity Rep'           => 9,
        'Analyst'               => 10,
        'Assessor'              => 10,
        'Company Rep'           => 11,
        'Client Rep'            => 11,
        'Regional Controller'   => 14,
        'Regional Co-ordinator' => 14,
        'Regional Coordinator'  => 14,
        'Vounteer with DBS'     => 15,
        'Volunteer with DBS'    => 15,
    );
    
    return $role_map;

}
